<?php
/**
 * includes/subpage-data.php
 * Conteúdo curado das páginas de destino (cidade) e de curso.
 * Usado por includes/subpage-render.php e pelos ficheiros finos
 * destino-*.php / curso-*.php.
 */

const DESTINOS = [
    'lisboa' => [
        'nome' => 'Lisboa',
        'eyebrow' => 'Capital de Portugal',
        'resumo' => 'A capital portuguesa é a cidade com mais universidades, mais cursos e a maior comunidade brasileira do país — o ponto de entrada mais procurado por quem vem do Brasil.',
        'imagem' => 'cidade-lisboa',
        'highlights' => [
            ['icon' => 'bi-mortarboard', 'titulo' => 'Mais universidades', 'texto' => 'Maior oferta de cursos e instituições de todo o país.'],
            ['icon' => 'bi-people', 'titulo' => 'Maior comunidade BR', 'texto' => 'A cidade com mais brasileiros a estudar em Portugal.'],
            ['icon' => 'bi-cash-coin', 'titulo' => 'Custo de vida mais alto', 'texto' => 'Topo da faixa nacional — compensa com mais oportunidades.'],
        ],
        'universidades' => [
            'Universidade de Lisboa (ULisboa)',
            'Universidade NOVA de Lisboa',
            'ISCTE — Instituto Universitário de Lisboa',
            'Universidade Católica Portuguesa (Lisboa)',
            'Instituto Superior Técnico',
            'ISEG — Lisbon School of Economics & Management',
        ],
        'custo_vida' => 'Entre 900€ e 1.200€/mês (quarto/alojamento incluído) — o topo da faixa nacional, compensado pela maior oferta de estágios e emprego.',
        'vida_academica' => 'Cidade grande, cosmopolita, com vida noturna intensa e a maior comunidade de estudantes brasileiros de Portugal — é normalmente mais fácil adaptar-se aqui nos primeiros meses.',
        'cursos_destaque' => ['medicina', 'direito', 'gestao', 'engenharia-informatica'],
        'transportes' => 'Metro, comboios urbanos e aeroporto dentro da cidade — a rede de transportes mais completa do país.',
    ],
    'porto' => [
        'nome' => 'Porto',
        'eyebrow' => 'Tradição e Douro',
        'resumo' => 'A segunda maior cidade do país, com forte tradição universitária, arquitetura reconhecida internacionalmente e um custo de vida mais acessível do que Lisboa.',
        'imagem' => 'cidade-porto',
        'highlights' => [
            ['icon' => 'bi-building', 'titulo' => 'FAUP de referência', 'texto' => 'Escola de Arquitetura com prestígio internacional.'],
            ['icon' => 'bi-cash-coin', 'titulo' => 'Mais acessível', 'texto' => 'Custo de vida abaixo de Lisboa, com qualidade equivalente.'],
            ['icon' => 'bi-water', 'titulo' => 'À beira do Douro', 'texto' => 'Cidade compacta, caminhável, à beira-rio.'],
        ],
        'universidades' => [
            'Universidade do Porto',
            'Universidade Católica Portuguesa (Porto)',
            'ISEP — Instituto Superior de Engenharia do Porto',
        ],
        'custo_vida' => 'Entre 750€ e 1.000€/mês — ligeiramente abaixo de Lisboa, com boa relação custo-benefício.',
        'vida_academica' => 'Segunda maior cidade do país, com identidade universitária forte e uma das escolas de arquitetura mais respeitadas da Europa (FAUP).',
        'cursos_destaque' => ['arquitetura', 'engenharia-informatica', 'medicina', 'gestao'],
        'transportes' => 'Metro extenso, centro histórico caminhável e ligações ferroviárias diretas a Lisboa (~2h45) e a Espanha.',
    ],
    'coimbra' => [
        'nome' => 'Coimbra',
        'eyebrow' => 'A cidade universitária',
        'resumo' => 'Sede da universidade mais antiga de Portugal (fundada em 1290, Património Mundial da UNESCO), Coimbra é sinónimo de vida académica — tradições, repúblicas de estudantes e um ambiente construído à volta da universidade.',
        'imagem' => 'cidade-coimbra',
        'highlights' => [
            ['icon' => 'bi-bank', 'titulo' => 'Fundada em 1290', 'texto' => 'A universidade mais antiga de Portugal, Património da UNESCO.'],
            ['icon' => 'bi-mortarboard', 'titulo' => 'Cidade universitária', 'texto' => 'Vida académica no centro de tudo, tradições únicas.'],
            ['icon' => 'bi-cash-coin', 'titulo' => 'Custo intermédio', 'texto' => 'Mais barata que Lisboa e Porto.'],
        ],
        'universidades' => [
            'Universidade de Coimbra',
        ],
        'custo_vida' => 'Entre 600€ e 850€/mês — sensivelmente mais barata que Lisboa e Porto.',
        'vida_academica' => 'Cidade pequena e antiga, construída à volta da universidade, com tradições próprias (como a Queima das Fitas) e uma comunidade estudantil muito unida.',
        'cursos_destaque' => ['direito', 'medicina'],
        'transportes' => 'Localização central no país, com ligações ferroviárias diretas a Lisboa e Porto (cerca de 1h30-2h).',
    ],
    'braga' => [
        'nome' => 'Braga',
        'eyebrow' => 'Jovem e em crescimento',
        'resumo' => 'Uma das cidades mais jovens da Europa (em proporção de população estudantil), com uma universidade forte em engenharia e tecnologia e um custo de vida bastante acessível.',
        'imagem' => 'cidade-braga',
        'highlights' => [
            ['icon' => 'bi-cpu', 'titulo' => 'Polo tecnológico', 'texto' => 'Forte em engenharia, próxima de empresas de tecnologia.'],
            ['icon' => 'bi-graph-up-arrow', 'titulo' => 'Cidade em crescimento', 'texto' => 'Economia dinâmica, população jovem.'],
            ['icon' => 'bi-cash-coin', 'titulo' => 'Muito acessível', 'texto' => 'Uma das cidades universitárias mais baratas do país.'],
        ],
        'universidades' => [
            'Universidade do Minho',
        ],
        'custo_vida' => 'Entre 600€ e 800€/mês — uma das cidades universitárias mais acessíveis do país.',
        'vida_academica' => 'Cidade jovem e em crescimento económico, a cerca de 1h do Porto, com boa relação custo-benefício para quem procura uma cidade mais calma.',
        'cursos_destaque' => ['engenharia-informatica', 'gestao'],
        'transportes' => 'Boas ligações rodoviárias e ferroviárias ao Porto (~1h) e ao resto do Minho.',
    ],
    'faro' => [
        'nome' => 'Faro',
        'eyebrow' => 'Sol o ano inteiro',
        'resumo' => 'Capital do Algarve, com clima ameno durante todo o ano, praias a poucos minutos e o custo de vida mais baixo entre as principais cidades universitárias portuguesas.',
        'imagem' => 'cidade-faro',
        'highlights' => [
            ['icon' => 'bi-sun', 'titulo' => 'Clima o ano todo', 'texto' => 'Mais horas de sol do que qualquer outra região do país.'],
            ['icon' => 'bi-water', 'titulo' => 'Praias a 10 minutos', 'texto' => 'Algarve à porta de casa.'],
            ['icon' => 'bi-cash-coin', 'titulo' => 'Mais barata', 'texto' => 'Custo de vida mais baixo entre as cidades universitárias.'],
        ],
        'universidades' => [
            'Universidade do Algarve',
        ],
        'custo_vida' => 'Entre 500€ e 750€/mês — a opção mais acessível entre as cidades cobertas aqui.',
        'vida_academica' => 'Cidade menor, ligada à economia do turismo e do mar, com um ritmo de vida mais tranquilo e praias a poucos minutos do campus.',
        'cursos_destaque' => ['gestao'],
        'transportes' => 'Aeroporto internacional na própria cidade e boas ligações rodoviárias a toda a região do Algarve.',
    ],
    'evora' => [
        'nome' => 'Évora',
        'eyebrow' => 'Património da UNESCO',
        'resumo' => 'Cidade histórica classificada Património Mundial da UNESCO, no coração do Alentejo — pequena, tranquila e uma das mais acessíveis para estudar em Portugal.',
        'imagem' => 'cidade-evora',
        'highlights' => [
            ['icon' => 'bi-bank2', 'titulo' => 'Património UNESCO', 'texto' => 'Centro histórico classificado, arquitetura romana e medieval.'],
            ['icon' => 'bi-flower1', 'titulo' => 'Coração do Alentejo', 'texto' => 'Região vinícola e agrícola, ritmo de vida calmo.'],
            ['icon' => 'bi-cash-coin', 'titulo' => 'Muito acessível', 'texto' => 'Uma das cidades mais baratas para estudar no país.'],
        ],
        'universidades' => [
            'Universidade de Évora',
        ],
        'custo_vida' => 'Entre 500€ e 700€/mês — entre as cidades mais acessíveis para estudar em Portugal.',
        'vida_academica' => 'Cidade pequena e histórica, com ambiente académico próximo e tranquilo, ideal para quem prefere fugir da agitação das grandes cidades.',
        'cursos_destaque' => [],
        'transportes' => 'Ligações rodoviárias e ferroviárias a Lisboa (cerca de 1h30).',
    ],
    'aveiro' => [
        'nome' => 'Aveiro',
        'eyebrow' => 'A "Veneza portuguesa"',
        'resumo' => 'Conhecida pelos seus canais e barcos moliceiros, Aveiro é também um dos maiores polos de engenharia e tecnologia de Portugal, com forte ligação à indústria.',
        'imagem' => 'cidade-aveiro',
        'highlights' => [
            ['icon' => 'bi-cpu', 'titulo' => 'Polo de engenharia', 'texto' => 'Forte reputação em ciências e tecnologia.'],
            ['icon' => 'bi-water', 'titulo' => 'Canais e praias', 'texto' => 'Cidade costeira, conhecida como a "Veneza portuguesa".'],
            ['icon' => 'bi-cash-coin', 'titulo' => 'Custo acessível', 'texto' => 'Mais barata que Lisboa e Porto.'],
        ],
        'universidades' => [
            'Universidade de Aveiro',
        ],
        'custo_vida' => 'Entre 600€ e 800€/mês — acessível, com boa qualidade de vida costeira.',
        'vida_academica' => 'Cidade de média dimensão, com forte ligação entre a universidade e a indústria tecnológica, e praias a curta distância do centro.',
        'cursos_destaque' => ['engenharia-informatica'],
        'transportes' => 'Na linha ferroviária principal entre Porto (~45 min) e Lisboa (~2h15).',
    ],
];

const CURSOS = [
    'medicina' => [
        'nome' => 'Medicina',
        'eyebrow' => 'Ciências da Saúde',
        'icone' => 'bi-heart-pulse',
        'resumo' => 'Mestrado Integrado de 6 anos, com vagas próprias no Concurso Especial de Estudantes Internacionais — uma das áreas mais procuradas por brasileiros, e também das mais competitivas.',
        'duracao' => 'Mestrado Integrado — 6 anos',
        'highlights' => [
            ['icon' => 'bi-mortarboard', 'titulo' => '6 anos', 'texto' => 'Mestrado Integrado, sem separação entre licenciatura e mestrado.'],
            ['icon' => 'bi-graph-up', 'titulo' => 'Muito competitivo', 'texto' => 'Vagas limitadas mesmo dentro do Concurso Especial.'],
            ['icon' => 'bi-globe-europe-africa', 'titulo' => 'Diploma na UE', 'texto' => 'Reconhecido em toda a União Europeia.'],
        ],
        'universidades_destaque' => ['lisboa', 'porto', 'coimbra'],
        'observacoes' => 'Para exercer no Brasil depois de formado em Portugal, é necessário passar pelo processo de revalidação de diploma (Revalida) junto de uma universidade brasileira — vale sempre confirmar os requisitos atuais antes de decidir.',
        'saidas' => 'Médico(a) generalista, seguido de especialização (internato médico), em Portugal ou noutro país da UE.',
    ],
    'engenharia-informatica' => [
        'nome' => 'Engenharia Informática',
        'eyebrow' => 'Engenharia e Tecnologia',
        'icone' => 'bi-cpu',
        'resumo' => 'Uma das áreas com maior empregabilidade em Portugal, beneficiando do forte crescimento do setor tecnológico português e da presença de empresas internacionais no país.',
        'duracao' => 'Licenciatura (3 anos) + Mestrado (2 anos), ou Mestrado Integrado de 5 anos, conforme a instituição.',
        'highlights' => [
            ['icon' => 'bi-briefcase', 'titulo' => 'Alta empregabilidade', 'texto' => 'Setor tech português em forte crescimento.'],
            ['icon' => 'bi-building', 'titulo' => 'Empresas internacionais', 'texto' => 'Muitas multinacionais tech com sede ou hub em Portugal.'],
            ['icon' => 'bi-globe-europe-africa', 'titulo' => 'Mobilidade na UE', 'texto' => 'Diploma reconhecido em toda a União Europeia.'],
        ],
        'universidades_destaque' => ['lisboa', 'porto', 'braga', 'aveiro'],
        'observacoes' => 'Portugal tornou-se um destino relevante para startups e centros de desenvolvimento de empresas tecnológicas internacionais, o que amplia as oportunidades de estágio durante o curso.',
        'saidas' => 'Desenvolvimento de software, dados, ciber­segurança, ou continuação para investigação/doutoramento.',
    ],
    'direito' => [
        'nome' => 'Direito',
        'eyebrow' => 'Ciências Jurídicas',
        'icone' => 'bi-bank',
        'resumo' => 'Uma das formações mais tradicionais de Portugal, com a faculdade mais antiga do país em Coimbra, e forte procura por estudantes brasileiros ligados à área jurídica e empresarial.',
        'duracao' => 'Licenciatura (3 anos) + Mestrado (2 anos) para habilitação plena.',
        'highlights' => [
            ['icon' => 'bi-bank2', 'titulo' => 'Tradição centenária', 'texto' => 'Coimbra tem a faculdade de Direito mais antiga do país.'],
            ['icon' => 'bi-briefcase', 'titulo' => 'Mercado jurídico europeu', 'texto' => 'Base para atuar em Direito da UE e internacional.'],
            ['icon' => 'bi-info-circle', 'titulo' => 'Habilitações separadas', 'texto' => 'Diploma português não substitui a OAB no Brasil.'],
        ],
        'universidades_destaque' => ['coimbra', 'lisboa', 'porto'],
        'observacoes' => 'O diploma português habilita a exercer em Portugal (após exame de acesso à Ordem dos Advogados), mas não substitui a OAB para exercer no Brasil — são ordens profissionais distintas.',
        'saidas' => 'Advocacia, magistratura (via exame de acesso), consultoria jurídica em empresas com operações na UE.',
    ],
    'gestao' => [
        'nome' => 'Gestão',
        'eyebrow' => 'Economia e Gestão',
        'icone' => 'bi-graph-up-arrow',
        'resumo' => 'Formação com forte procura entre estudantes brasileiros, apoiada em escolas de referência europeia como o ISEG e a NOVA SBE, com boa rede de estágios em empresas portuguesas e europeias.',
        'duracao' => 'Licenciatura (3 anos) + Mestrado (2 anos).',
        'highlights' => [
            ['icon' => 'bi-mortarboard', 'titulo' => 'Escolas de referência', 'texto' => 'ISEG e NOVA SBE entre as mais reconhecidas da Europa.'],
            ['icon' => 'bi-briefcase', 'titulo' => 'Rede de estágios', 'texto' => 'Ligação forte a empresas portuguesas e europeias.'],
            ['icon' => 'bi-globe-europe-africa', 'titulo' => 'Saída internacional', 'texto' => 'Boa base para carreira em qualquer país da UE.'],
        ],
        'universidades_destaque' => ['lisboa', 'porto', 'braga', 'faro'],
        'observacoes' => 'Muitas instituições oferecem também especializações em Marketing, Finanças ou Gestão Hoteleira/Turismo, especialmente nas cidades do Algarve.',
        'saidas' => 'Gestão empresarial, consultoria, finanças, marketing, com boa mobilidade para trabalhar noutros países da UE.',
    ],
    'enfermagem' => [
        'nome' => 'Enfermagem',
        'eyebrow' => 'Ciências da Saúde',
        'icone' => 'bi-heart',
        'resumo' => 'Profissão regulada pela Ordem dos Enfermeiros, com forte procura no mercado de trabalho português e europeu — uma das áreas da saúde com mais oportunidades de emprego imediato após a formação.',
        'duracao' => 'Licenciatura de 4 anos (mais longa do que a maioria das licenciaturas portuguesas).',
        'highlights' => [
            ['icon' => 'bi-briefcase', 'titulo' => 'Forte procura', 'texto' => 'Défice de enfermeiros em Portugal e na Europa.'],
            ['icon' => 'bi-hospital', 'titulo' => 'Saída rápida', 'texto' => 'Empregabilidade elevada logo após a licenciatura.'],
            ['icon' => 'bi-globe-europe-africa', 'titulo' => 'Mobilidade na UE', 'texto' => 'Diploma reconhecido em toda a União Europeia.'],
        ],
        'universidades_destaque' => ['lisboa', 'porto', 'coimbra'],
        'observacoes' => 'A profissão é regulada pela Ordem dos Enfermeiros, com inscrição obrigatória para exercer em Portugal.',
        'saidas' => 'Hospitais, cuidados de saúde primários, com boa mobilidade para trabalhar noutros países da UE.',
    ],
    'arquitetura' => [
        'nome' => 'Arquitetura',
        'eyebrow' => 'Arquitetura e Urbanismo',
        'icone' => 'bi-building',
        'resumo' => 'Portugal tem uma das escolas de arquitetura mais respeitadas do mundo — a FAUP, no Porto, associada a nomes como Álvaro Siza Vieira e Eduardo Souto de Moura, ambos vencedores do Prémio Pritzker.',
        'duracao' => 'Mestrado Integrado — 5 anos.',
        'highlights' => [
            ['icon' => 'bi-award', 'titulo' => 'Prestígio internacional', 'texto' => 'Escola do Porto associada a dois Prémios Pritzker.'],
            ['icon' => 'bi-mortarboard', 'titulo' => '5 anos', 'texto' => 'Mestrado Integrado, formação completa numa só candidatura.'],
            ['icon' => 'bi-globe-europe-africa', 'titulo' => 'Diploma na UE', 'texto' => 'Reconhecido em toda a União Europeia.'],
        ],
        'universidades_destaque' => ['porto', 'lisboa', 'coimbra'],
        'observacoes' => 'A "Escola do Porto" (FAUP) é uma referência mundial em arquitetura, com um estilo próprio estudado em faculdades por todo o mundo.',
        'saidas' => 'Ateliers de arquitetura, urbanismo, ou continuação para investigação e doutoramento.',
    ],
    'psicologia' => [
        'nome' => 'Psicologia',
        'eyebrow' => 'Ciências Sociais e Humanas',
        'icone' => 'bi-person-heart',
        'resumo' => 'Para exercer como psicólogo em Portugal é necessário o grau de Mestre, com a profissão regulada pela Ordem dos Psicólogos Portugueses — uma formação sólida e com boa procura em toda a Europa.',
        'duracao' => 'Licenciatura (3 anos) + Mestrado (2 anos) — o mestrado é obrigatório para exercer.',
        'highlights' => [
            ['icon' => 'bi-mortarboard', 'titulo' => 'Mestrado obrigatório', 'texto' => 'Só com o grau de Mestre é possível exercer.'],
            ['icon' => 'bi-people', 'titulo' => 'Várias especializações', 'texto' => 'Clínica, organizacional, educacional, entre outras.'],
            ['icon' => 'bi-globe-europe-africa', 'titulo' => 'Diploma na UE', 'texto' => 'Reconhecido em toda a União Europeia.'],
        ],
        'universidades_destaque' => ['lisboa', 'porto', 'braga'],
        'observacoes' => 'A profissão é regulada pela Ordem dos Psicólogos Portugueses, com inscrição obrigatória para exercer em Portugal.',
        'saidas' => 'Psicologia clínica, organizacional ou educacional, em Portugal ou noutro país da UE.',
    ],
    'fisioterapia' => [
        'nome' => 'Fisioterapia',
        'eyebrow' => 'Ciências da Saúde',
        'icone' => 'bi-activity',
        'resumo' => 'Formação de ciclo curto e forte procura no mercado, com boas oportunidades em clínicas, hospitais e no desporto, tanto em Portugal como no resto da União Europeia.',
        'duracao' => 'Licenciatura de 3 a 4 anos, normalmente em escolas superiores de saúde (politécnicos).',
        'highlights' => [
            ['icon' => 'bi-clock', 'titulo' => 'Formação mais curta', 'texto' => '3 a 4 anos, entrada mais rápida no mercado.'],
            ['icon' => 'bi-briefcase', 'titulo' => 'Forte procura', 'texto' => 'Clínicas, hospitais e clubes desportivos.'],
            ['icon' => 'bi-globe-europe-africa', 'titulo' => 'Mobilidade na UE', 'texto' => 'Diploma reconhecido em toda a União Europeia.'],
        ],
        'universidades_destaque' => ['lisboa', 'porto', 'coimbra'],
        'observacoes' => 'Costuma ser lecionada em escolas superiores de saúde (ensino politécnico), com forte componente prática desde os primeiros anos.',
        'saidas' => 'Clínicas privadas, hospitais, clubes desportivos, com boa mobilidade para trabalhar noutros países da UE.',
    ],
    'economia' => [
        'nome' => 'Economia',
        'eyebrow' => 'Economia e Gestão',
        'icone' => 'bi-bar-chart-line',
        'resumo' => 'Formação analítica de referência, com escolas como o ISEG e a FEP entre as mais respeitadas da Europa — boa base para banca, consultoria e organismos internacionais.',
        'duracao' => 'Licenciatura (3 anos) + Mestrado (2 anos).',
        'highlights' => [
            ['icon' => 'bi-mortarboard', 'titulo' => 'Escolas de referência', 'texto' => 'ISEG e FEP entre as mais respeitadas da Europa.'],
            ['icon' => 'bi-bank', 'titulo' => 'Banca e consultoria', 'texto' => 'Forte procura por parte de bancos e consultoras.'],
            ['icon' => 'bi-globe-europe-africa', 'titulo' => 'Organismos internacionais', 'texto' => 'Base sólida para carreira em instituições da UE.'],
        ],
        'universidades_destaque' => ['lisboa', 'porto', 'braga'],
        'observacoes' => 'Muitas vezes lecionada na mesma faculdade que Gestão, com currículo mais analítico e quantitativo.',
        'saidas' => 'Banca, consultoria, análise financeira, organismos internacionais e administração pública.',
    ],
    'marketing' => [
        'nome' => 'Marketing',
        'eyebrow' => 'Economia e Gestão',
        'icone' => 'bi-megaphone',
        'resumo' => 'Curso com procura crescente, muitas vezes como especialização dentro de Gestão, ligado a marcas e empresas com operações em Portugal e no resto da Europa.',
        'duracao' => 'Licenciatura (3 anos) + Mestrado (2 anos).',
        'highlights' => [
            ['icon' => 'bi-graph-up', 'titulo' => 'Procura crescente', 'texto' => 'Área em expansão nas empresas portuguesas.'],
            ['icon' => 'bi-briefcase', 'titulo' => 'Ligação à indústria', 'texto' => 'Estágios frequentes em marcas e agências.'],
            ['icon' => 'bi-globe-europe-africa', 'titulo' => 'Mobilidade na UE', 'texto' => 'Diploma reconhecido em toda a União Europeia.'],
        ],
        'universidades_destaque' => ['lisboa', 'porto'],
        'observacoes' => 'Em várias instituições é oferecido como especialização de Gestão em vez de licenciatura própria — vale confirmar a estrutura exata do curso.',
        'saidas' => 'Marketing digital, gestão de marca, comunicação empresarial, agências de publicidade.',
    ],
    'contabilidade' => [
        'nome' => 'Contabilidade',
        'eyebrow' => 'Economia e Gestão',
        'icone' => 'bi-calculator',
        'resumo' => 'Formação de ciclo curto com forte procura no mercado de trabalho, frequentemente oferecida em escolas superiores de gestão (politécnicos).',
        'duracao' => 'Licenciatura de 3 anos, normalmente em escolas superiores de gestão (politécnicos).',
        'highlights' => [
            ['icon' => 'bi-clock', 'titulo' => 'Formação mais curta', 'texto' => '3 anos, entrada mais rápida no mercado.'],
            ['icon' => 'bi-briefcase', 'titulo' => 'Forte procura', 'texto' => 'Empresas de todas as dimensões precisam de contabilistas.'],
            ['icon' => 'bi-globe-europe-africa', 'titulo' => 'Mobilidade na UE', 'texto' => 'Diploma reconhecido em toda a União Europeia.'],
        ],
        'universidades_destaque' => ['lisboa', 'porto', 'coimbra'],
        'observacoes' => 'Para exercer como contabilista certificado em Portugal é necessária inscrição na Ordem dos Contabilistas Certificados (OCC).',
        'saidas' => 'Contabilidade, auditoria, fiscalidade, em empresas ou em prática de contabilista certificado.',
    ],
    'engenharia-civil' => [
        'nome' => 'Engenharia Civil',
        'eyebrow' => 'Engenharia e Tecnologia',
        'icone' => 'bi-building-gear',
        'resumo' => 'Uma das engenharias mais tradicionais de Portugal, com forte procura ligada à construção, infraestruturas e reabilitação urbana.',
        'duracao' => 'Mestrado Integrado — 5 anos.',
        'highlights' => [
            ['icon' => 'bi-mortarboard', 'titulo' => '5 anos', 'texto' => 'Mestrado Integrado, formação completa numa só candidatura.'],
            ['icon' => 'bi-cone-striped', 'titulo' => 'Construção e infraestrutura', 'texto' => 'Ligação direta ao setor da construção português.'],
            ['icon' => 'bi-globe-europe-africa', 'titulo' => 'Diploma na UE', 'texto' => 'Reconhecido em toda a União Europeia.'],
        ],
        'universidades_destaque' => ['lisboa', 'porto', 'coimbra'],
        'observacoes' => 'Para assinar projetos como engenheiro responsável é necessária inscrição na Ordem dos Engenheiros.',
        'saidas' => 'Projeto e fiscalização de obras, construção, infraestruturas, reabilitação urbana.',
    ],
    'engenharia-mecanica' => [
        'nome' => 'Engenharia Mecânica',
        'eyebrow' => 'Engenharia e Tecnologia',
        'icone' => 'bi-gear',
        'resumo' => 'Formação versátil com aplicação industrial, automóvel e energética, e boa empregabilidade em Portugal e no resto da Europa.',
        'duracao' => 'Mestrado Integrado — 5 anos.',
        'highlights' => [
            ['icon' => 'bi-mortarboard', 'titulo' => '5 anos', 'texto' => 'Mestrado Integrado, formação completa numa só candidatura.'],
            ['icon' => 'bi-briefcase', 'titulo' => 'Aplicação industrial', 'texto' => 'Indústria automóvel, energética e de manufatura.'],
            ['icon' => 'bi-globe-europe-africa', 'titulo' => 'Diploma na UE', 'texto' => 'Reconhecido em toda a União Europeia.'],
        ],
        'universidades_destaque' => ['lisboa', 'porto', 'aveiro'],
        'observacoes' => 'Para assinar projetos como engenheiro responsável é necessária inscrição na Ordem dos Engenheiros.',
        'saidas' => 'Indústria automóvel, energética, manufatura, projeto e manutenção industrial.',
    ],
    'engenharia-eletrotecnica' => [
        'nome' => 'Engenharia Eletrotécnica',
        'eyebrow' => 'Engenharia e Tecnologia',
        'icone' => 'bi-lightning-charge',
        'resumo' => 'Cobre energia, automação e telecomunicações — uma área em crescimento com a transição energética e a digitalização da indústria portuguesa.',
        'duracao' => 'Mestrado Integrado — 5 anos.',
        'highlights' => [
            ['icon' => 'bi-mortarboard', 'titulo' => '5 anos', 'texto' => 'Mestrado Integrado, formação completa numa só candidatura.'],
            ['icon' => 'bi-lightning', 'titulo' => 'Transição energética', 'texto' => 'Forte procura ligada a energias renováveis.'],
            ['icon' => 'bi-globe-europe-africa', 'titulo' => 'Diploma na UE', 'texto' => 'Reconhecido em toda a União Europeia.'],
        ],
        'universidades_destaque' => ['lisboa', 'porto', 'aveiro'],
        'observacoes' => 'Costuma incluir especializações em automação, energia ou telecomunicações consoante a instituição.',
        'saidas' => 'Energia, automação industrial, telecomunicações, energias renováveis.',
    ],
    'medicina-dentaria' => [
        'nome' => 'Medicina Dentária',
        'eyebrow' => 'Ciências da Saúde',
        'icone' => 'bi-emoji-smile',
        'resumo' => 'Mestrado Integrado de 5 anos com forte componente prática clínica desde os primeiros anos, e boa saída profissional em Portugal e na Europa.',
        'duracao' => 'Mestrado Integrado — 5 anos.',
        'highlights' => [
            ['icon' => 'bi-mortarboard', 'titulo' => '5 anos', 'texto' => 'Mestrado Integrado, formação completa numa só candidatura.'],
            ['icon' => 'bi-clipboard-pulse', 'titulo' => 'Prática clínica cedo', 'texto' => 'Contacto com pacientes desde os primeiros anos.'],
            ['icon' => 'bi-globe-europe-africa', 'titulo' => 'Diploma na UE', 'texto' => 'Reconhecido em toda a União Europeia.'],
        ],
        'universidades_destaque' => ['lisboa', 'porto', 'coimbra'],
        'observacoes' => 'A profissão é regulada pela Ordem dos Médicos Dentistas, com inscrição obrigatória para exercer em Portugal.',
        'saidas' => 'Clínica dentária privada, hospitais, ou continuação para especialização.',
    ],
    'medicina-veterinaria' => [
        'nome' => 'Medicina Veterinária',
        'eyebrow' => 'Ciências da Saúde',
        'icone' => 'bi-heart-pulse-fill',
        'resumo' => 'Mestrado Integrado de 6 anos, com forte tradição em cidades ligadas à agricultura e pecuária, como Évora e Vila Real.',
        'duracao' => 'Mestrado Integrado — 6 anos.',
        'highlights' => [
            ['icon' => 'bi-mortarboard', 'titulo' => '6 anos', 'texto' => 'Mestrado Integrado, sem separação entre licenciatura e mestrado.'],
            ['icon' => 'bi-tree', 'titulo' => 'Tradição agrícola', 'texto' => 'Forte em cidades como Évora e Vila Real.'],
            ['icon' => 'bi-globe-europe-africa', 'titulo' => 'Diploma na UE', 'texto' => 'Reconhecido em toda a União Europeia.'],
        ],
        'universidades_destaque' => ['lisboa', 'evora'],
        'observacoes' => 'A profissão é regulada pela Ordem dos Médicos Veterinários, com inscrição obrigatória para exercer em Portugal.',
        'saidas' => 'Clínica veterinária, produção animal, saúde pública veterinária.',
    ],
    'farmacia' => [
        'nome' => 'Ciências Farmacêuticas',
        'eyebrow' => 'Ciências da Saúde',
        'icone' => 'bi-capsule',
        'resumo' => 'Mestrado Integrado de 5 anos, com boas saídas em farmácia comunitária, hospitalar e na indústria farmacêutica.',
        'duracao' => 'Mestrado Integrado — 5 anos.',
        'highlights' => [
            ['icon' => 'bi-mortarboard', 'titulo' => '5 anos', 'texto' => 'Mestrado Integrado, formação completa numa só candidatura.'],
            ['icon' => 'bi-briefcase', 'titulo' => 'Indústria farmacêutica', 'texto' => 'Saídas em farmácia, hospitais e laboratórios.'],
            ['icon' => 'bi-globe-europe-africa', 'titulo' => 'Diploma na UE', 'texto' => 'Reconhecido em toda a União Europeia.'],
        ],
        'universidades_destaque' => ['lisboa', 'porto', 'coimbra'],
        'observacoes' => 'A profissão é regulada pela Ordem dos Farmacêuticos, com inscrição obrigatória para exercer em Portugal.',
        'saidas' => 'Farmácia comunitária, farmácia hospitalar, indústria farmacêutica, investigação.',
    ],
    'nutricao' => [
        'nome' => 'Ciências da Nutrição',
        'eyebrow' => 'Ciências da Saúde',
        'icone' => 'bi-egg-fried',
        'resumo' => 'A Faculdade de Ciências da Nutrição e Alimentação da Universidade do Porto é uma referência nacional nesta área, com forte ligação à saúde pública.',
        'duracao' => 'Licenciatura (3 anos) + Mestrado (2 anos) — o mestrado é obrigatório para exercer.',
        'highlights' => [
            ['icon' => 'bi-mortarboard', 'titulo' => 'Mestrado obrigatório', 'texto' => 'Só com o grau de Mestre é possível exercer.'],
            ['icon' => 'bi-award', 'titulo' => 'Referência no Porto', 'texto' => 'FCNAUP é referência nacional na área.'],
            ['icon' => 'bi-globe-europe-africa', 'titulo' => 'Diploma na UE', 'texto' => 'Reconhecido em toda a União Europeia.'],
        ],
        'universidades_destaque' => ['porto', 'coimbra', 'faro'],
        'observacoes' => 'A profissão é regulada pela Ordem dos Nutricionistas, com inscrição obrigatória para exercer em Portugal.',
        'saidas' => 'Nutrição clínica, saúde pública, indústria alimentar, desporto.',
    ],
    'ciencias-comunicacao' => [
        'nome' => 'Ciências da Comunicação',
        'eyebrow' => 'Ciências Sociais e Humanas',
        'icone' => 'bi-mic',
        'resumo' => 'Formação abrangente em jornalismo, comunicação empresarial e média, com boa procura por parte de brasileiros interessados em comunicação e media.',
        'duracao' => 'Licenciatura (3 anos) + Mestrado (2 anos).',
        'highlights' => [
            ['icon' => 'bi-newspaper', 'titulo' => 'Jornalismo e média', 'texto' => 'Formação em jornalismo, rádio, TV e digital.'],
            ['icon' => 'bi-briefcase', 'titulo' => 'Comunicação empresarial', 'texto' => 'Saída também para assessoria e relações públicas.'],
            ['icon' => 'bi-globe-europe-africa', 'titulo' => 'Diploma na UE', 'texto' => 'Reconhecido em toda a União Europeia.'],
        ],
        'universidades_destaque' => ['lisboa', 'braga', 'coimbra'],
        'observacoes' => 'Muitas instituições oferecem especializações em jornalismo, publicidade ou comunicação organizacional a partir do mestrado.',
        'saidas' => 'Jornalismo, comunicação empresarial, relações públicas, produção de conteúdo digital.',
    ],
    'relacoes-internacionais' => [
        'nome' => 'Relações Internacionais',
        'eyebrow' => 'Ciências Sociais e Humanas',
        'icone' => 'bi-globe',
        'resumo' => 'Formação com boa saída para diplomacia, organizações internacionais e ONGs, com Portugal como base natural para uma carreira ligada à lusofonia e à UE.',
        'duracao' => 'Licenciatura (3 anos) + Mestrado (2 anos).',
        'highlights' => [
            ['icon' => 'bi-flag', 'titulo' => 'Diplomacia', 'texto' => 'Base para carreira diplomática e organismos internacionais.'],
            ['icon' => 'bi-globe-europe-africa', 'titulo' => 'Porta de entrada na UE', 'texto' => 'Portugal como base para carreira europeia.'],
            ['icon' => 'bi-people', 'titulo' => 'Lusofonia', 'texto' => 'Ligação natural aos países de língua portuguesa.'],
        ],
        'universidades_destaque' => ['lisboa', 'braga'],
        'observacoes' => 'Frequentemente combinado com especializações em Direito Internacional, Estudos Europeus ou Cooperação para o Desenvolvimento.',
        'saidas' => 'Diplomacia, organizações internacionais, ONGs, cooperação internacional.',
    ],
    'turismo' => [
        'nome' => 'Turismo',
        'eyebrow' => 'Gestão e Serviços',
        'icone' => 'bi-airplane',
        'resumo' => 'Portugal é um dos destinos turísticos mais procurados da Europa, e o Algarve — região da Universidade do Algarve — é o centro nacional da formação em turismo e hotelaria.',
        'duracao' => 'Licenciatura (3 anos) + Mestrado (2 anos).',
        'highlights' => [
            ['icon' => 'bi-sun', 'titulo' => 'Algarve como base', 'texto' => 'Universidade do Algarve é referência na área.'],
            ['icon' => 'bi-briefcase', 'titulo' => 'Setor em crescimento', 'texto' => 'Turismo é um dos maiores setores da economia portuguesa.'],
            ['icon' => 'bi-globe-europe-africa', 'titulo' => 'Diploma na UE', 'texto' => 'Reconhecido em toda a União Europeia.'],
        ],
        'universidades_destaque' => ['faro', 'aveiro', 'lisboa'],
        'observacoes' => 'Muitas vezes combinado com especializações em Gestão Hoteleira, Eventos ou Marketing Turístico.',
        'saidas' => 'Gestão hoteleira, agências de viagens, eventos, organismos públicos de turismo.',
    ],
    'design' => [
        'nome' => 'Design',
        'eyebrow' => 'Artes e Design',
        'icone' => 'bi-palette',
        'resumo' => 'Cobre design de comunicação, produto e digital, com boas saídas em agências criativas, indústria e tecnologia.',
        'duracao' => 'Licenciatura (3 anos) + Mestrado (2 anos).',
        'highlights' => [
            ['icon' => 'bi-brush', 'titulo' => 'Várias especializações', 'texto' => 'Comunicação, produto, moda ou design digital.'],
            ['icon' => 'bi-briefcase', 'titulo' => 'Agências criativas', 'texto' => 'Boa ligação a agências e à indústria criativa.'],
            ['icon' => 'bi-globe-europe-africa', 'titulo' => 'Diploma na UE', 'texto' => 'Reconhecido em toda a União Europeia.'],
        ],
        'universidades_destaque' => ['aveiro', 'lisboa', 'porto'],
        'observacoes' => 'A Universidade de Aveiro tem um dos programas de Design mais reconhecidos do país.',
        'saidas' => 'Design gráfico e digital, design de produto, agências criativas, indústria.',
    ],
    'educacao-basica' => [
        'nome' => 'Educação Básica',
        'eyebrow' => 'Educação',
        'icone' => 'bi-book',
        'resumo' => 'Primeiro passo para quem quer ser professor em Portugal — a licenciatura habilita a continuar para um mestrado profissionalizante que dá acesso à docência.',
        'duracao' => 'Licenciatura de 3 anos, seguida de mestrado profissionalizante para lecionar.',
        'highlights' => [
            ['icon' => 'bi-mortarboard', 'titulo' => 'Caminho para a docência', 'texto' => 'Licenciatura + mestrado profissionalizante.'],
            ['icon' => 'bi-people', 'titulo' => 'Forte procura', 'texto' => 'Défice de professores em várias regiões do país.'],
            ['icon' => 'bi-globe-europe-africa', 'titulo' => 'Diploma na UE', 'texto' => 'Reconhecido em toda a União Europeia.'],
        ],
        'universidades_destaque' => ['braga', 'coimbra', 'lisboa'],
        'observacoes' => 'A licenciatura por si só não habilita para a docência — é preciso o mestrado profissionalizante correspondente ao nível de ensino pretendido.',
        'saidas' => 'Docência (após mestrado profissionalizante), educação não-formal, materiais pedagógicos.',
    ],
    'servico-social' => [
        'nome' => 'Serviço Social',
        'eyebrow' => 'Ciências Sociais e Humanas',
        'icone' => 'bi-hand-holding-heart',
        'resumo' => 'Formação vocacionada para a intervenção social, com forte procura em autarquias, IPSS e organizações não-governamentais em Portugal.',
        'duracao' => 'Licenciatura (3 anos) + Mestrado (2 anos).',
        'highlights' => [
            ['icon' => 'bi-people', 'titulo' => 'Intervenção social', 'texto' => 'Trabalho direto com comunidades e famílias.'],
            ['icon' => 'bi-briefcase', 'titulo' => 'Autarquias e IPSS', 'texto' => 'Forte procura em câmaras municipais e organizações sociais.'],
            ['icon' => 'bi-globe-europe-africa', 'titulo' => 'Diploma na UE', 'texto' => 'Reconhecido em toda a União Europeia.'],
        ],
        'universidades_destaque' => ['lisboa', 'porto'],
        'observacoes' => 'Área em processo de regulamentação profissional em Portugal — vale confirmar o estado atual junto da instituição.',
        'saidas' => 'Autarquias, IPSS, ONGs, hospitais, sistema de justiça.',
    ],
    'ciencias-desporto' => [
        'nome' => 'Ciências do Desporto',
        'eyebrow' => 'Ciências da Saúde',
        'icone' => 'bi-trophy',
        'resumo' => 'Cobre treino desportivo, exercício e saúde, e gestão do desporto — com boas saídas em clubes, ginásios e organismos desportivos.',
        'duracao' => 'Licenciatura (3 anos) + Mestrado (2 anos).',
        'highlights' => [
            ['icon' => 'bi-bicycle', 'titulo' => 'Treino e exercício', 'texto' => 'Especializações em treino desportivo e exercício e saúde.'],
            ['icon' => 'bi-briefcase', 'titulo' => 'Clubes e ginásios', 'texto' => 'Boa procura em clubes desportivos e ginásios.'],
            ['icon' => 'bi-globe-europe-africa', 'titulo' => 'Diploma na UE', 'texto' => 'Reconhecido em toda a União Europeia.'],
        ],
        'universidades_destaque' => ['lisboa', 'porto', 'coimbra'],
        'observacoes' => 'A Faculdade de Motricidade Humana (Lisboa) e a FADE (Porto) são referências nacionais nesta área.',
        'saidas' => 'Treino desportivo, ginásios, clubes, gestão do desporto, exercício e saúde.',
    ],
    'biologia' => [
        'nome' => 'Biologia',
        'eyebrow' => 'Ciências Exatas e Naturais',
        'icone' => 'bi-flower2',
        'resumo' => 'Formação de base para quem quer seguir investigação, conservação ou biotecnologia, com boa presença em cidades com forte tradição científica.',
        'duracao' => 'Licenciatura (3 anos) + Mestrado (2 anos).',
        'highlights' => [
            ['icon' => 'bi-mortarboard', 'titulo' => 'Base para investigação', 'texto' => 'Caminho natural para mestrado e doutoramento.'],
            ['icon' => 'bi-tree', 'titulo' => 'Conservação e ambiente', 'texto' => 'Boa saída em conservação e gestão ambiental.'],
            ['icon' => 'bi-globe-europe-africa', 'titulo' => 'Diploma na UE', 'texto' => 'Reconhecido em toda a União Europeia.'],
        ],
        'universidades_destaque' => ['coimbra', 'aveiro', 'porto', 'evora'],
        'observacoes' => 'Muitas vezes combinada com especializações em biotecnologia, biologia marinha ou ciências ambientais consoante a instituição.',
        'saidas' => 'Investigação, conservação e ambiente, biotecnologia, indústria farmacêutica e alimentar.',
    ],
    'ciencia-dados' => [
        'nome' => 'Ciência de Dados',
        'eyebrow' => 'Engenharia e Tecnologia',
        'icone' => 'bi-graph-up',
        'resumo' => 'Uma das áreas mais procuradas atualmente, com programas mais recentes mas já bem estabelecidos, e forte procura no mercado de trabalho português.',
        'duracao' => 'Licenciatura (3 anos) + Mestrado (2 anos), muitas vezes como mestrado a seguir a uma licenciatura em Informática, Matemática ou Gestão.',
        'highlights' => [
            ['icon' => 'bi-graph-up-arrow', 'titulo' => 'Alta empregabilidade', 'texto' => 'Uma das áreas mais procuradas pelo mercado atual.'],
            ['icon' => 'bi-database', 'titulo' => 'Programas recentes', 'texto' => 'Cursos novos mas já bem estabelecidos.'],
            ['icon' => 'bi-globe-europe-africa', 'titulo' => 'Diploma na UE', 'texto' => 'Reconhecido em toda a União Europeia.'],
        ],
        'universidades_destaque' => ['lisboa', 'aveiro', 'braga'],
        'observacoes' => 'A NOVA IMS (Lisboa) é uma referência nacional nesta área, muitas vezes através de mestrado dedicado.',
        'saidas' => 'Análise de dados, machine learning, business intelligence, investigação.',
    ],
    'belas-artes' => [
        'nome' => 'Belas-Artes',
        'eyebrow' => 'Artes e Design',
        'icone' => 'bi-easel',
        'resumo' => 'Formação artística tradicional, com faculdades próprias em Lisboa e Porto, para quem quer seguir pintura, escultura, artes multimédia ou curadoria.',
        'duracao' => 'Licenciatura (3 anos) + Mestrado (2 anos).',
        'highlights' => [
            ['icon' => 'bi-brush', 'titulo' => 'Faculdades próprias', 'texto' => 'Escolas de Belas-Artes em Lisboa e Porto.'],
            ['icon' => 'bi-image', 'titulo' => 'Várias disciplinas', 'texto' => 'Pintura, escultura, artes multimédia e curadoria.'],
            ['icon' => 'bi-globe-europe-africa', 'titulo' => 'Diploma na UE', 'texto' => 'Reconhecido em toda a União Europeia.'],
        ],
        'universidades_destaque' => ['lisboa', 'porto'],
        'observacoes' => 'Muitas candidaturas exigem prova de aptidão específica (portfólio ou prova prática), além da nota do ENEM.',
        'saidas' => 'Artista plástico, curadoria, ensino artístico, indústrias criativas.',
    ],
];
